### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by h00pl4**
"Getting Started" script

**Problem:**
Missing quote mark for session export of path including flutter bin directory

**Solution:**
Added missing quote mark

### CODE REVIEW

**Comment by XertroV** [comment]
Thanks!

**Comment by KipCrossing** [comment]
@h00pl4 thanks for this. Are you looking to get involved? Happy to help if so.

**Comment by h00pl4** [comment]
Hey @XertroV / @KipCrossing, no worries!
Doing a bit of testing here and there will likely be the scope of my involvement for now. 😊

**Comment by KipCrossing** [comment]
@h00pl4 Sweet! I just noticed that you also forked the API and it looked like you were going deep. Feel free to come along to our dev meetups (Monday nights on discord).

**Comment by h00pl4** [comment]
@kipcrossing, hehe yeah I did. I was getting CORS violations when I was debugging the voting app in Chrome, and i was trying understand why. I never actually worked it out, cos I saw that you've turned CORS on in API Gateway, for all endpoints, and that was really the only thing that came to mind to check.
I've got a bit of standing catch up with friends on a Monday night, but I'll see how I go. What time do you meet?

**Comment by KipCrossing** [comment]
Yeah we dumped supporting web because of that (I'll remove it from the README). Flutter web seems to be still in its early stages. Might look at it again later but it's low priority. Plus, it's probably not a good idea to store private keys on a browser. 

Monday nights at 8pm NSW time. :)

**Comment by XertroV** [comment]
oh yeah CORS doesn't work on the API because you're not returning all the headers you need to. They aren't added to the request for you' they're _allowed_ the be added to the request, so you still have to add them to every response (a good reason to include some abstraction layers)

**Comment by XertroV** [comment]
particularly you need allowed origin and allowed methods, which needs OPTIONS and any other methods as used

**Comment by KipCrossing** [comment]
This convo can be continued on #1

**Pull request merged**
