### PR TITLE
Update application icon

### PR DESCRIPTION
**Pull request by connorhsm**
**Problem:**
Android application icon displaying incorrectly.

**Solution:**

- Made use of flutter-launcher-icons adaptive foreground and background attributes to better display the app logo on Android with a solid background.
- Updated Android fallback icon, also used as the iOS icon.
- Removed original icon PNG and SVG.

### CODE REVIEW

**Comment by connorhsm** [comment]
@XertroV Nothing from Atomist?

**Comment by XertroV** [comment]
> 
> 
> @XertroV Nothing from Atomist?

There was an error on the 7th for like an hour (not sure if it was my end or theirs) and looks like the automatic reconnection didn't work. Restarted all the SDMs

**Comment by XertroV** [comment]
oh, actually maybe they were fine - not sure. However, this is a PR from _your_ repo, and there's a filter on the source (needs to be voteflux organisation) at the moment.

**Comment by XertroV** [comment]
curious, the checks are registering here, but are the same checks as here: https://github.com/voteflux/voting_app/pull/124 (which I created to trigger the thing)

so must be by sha hash

**Comment by XertroV** [comment]
@connorhsm - you should be able to push to https://github.com/voteflux/voting_app/tree/update-icons

**Comment by connorhsm** [comment]
Thanks @XertroV 
Should I close this PR and open a new one from the branch > master?

**Comment by XertroV** [comment]
> Thanks @XertroV
> Should I close this PR and open a new one from the branch > master?

You can just change the target of this PR. I've pushed your commits to this repo already (same branch name I think). #124 was the PR I opened to check things were working.

I will review on the weekend if it's not reviewed by someone else before then.

**Comment by connorhsm** [comment]
As far as I can see, I can't modify the repo/branch that the PR is comparing from.
Given that the checks are now functioning for this PR and have passed successfully, I would assume there is no issue with continuing with this PR. Please advise otherwise.

Awaiting review.

**Comment by XertroV** [comment]
> Given that the checks are now functioning for this PR and have passed successfully, I would assume there is no issue with continuing with this PR. Please advise otherwise.

That's correct. I'll check your permissions b/c you should be able to, though maybe you're only in python groups or something.

> Awaiting review.

Ack @KipCrossing @oscarmanderj ? (Like I said, will review this weekend in lieu of any other reviewer)

**Pull request merged**
