### PR TITLE
User page

### PR DESCRIPTION
**Pull request by oscarmanderj**
**Problem:**
No user profile page

**Solution:**
Made profile page to design spec

### CODE REVIEW

**Review by KipCrossing — CHANGES_REQUESTED** [review]
Looking sexy!

A few things

- [ ] A back button snuck into the user page that takes the user to the onboarding slides:

Screenshot from 2021-01-23 10-27-25

- [ ] the **voted - Watching** switch doesn't work

**Comment by oscarmanderj** [comment]
3 request changes made - Please review

**Review by KipCrossing — APPROVED** [review]
Perfect!

**Comment by KipCrossing** [comment]
closes #194
closes #199

**Pull request merged**
