### PR TITLE
UI colours

### PR DESCRIPTION
**Pull request by oscarmanderj**
**Problem:**
UI not reflective of new UI.

This PR is not an entire completion of the rework, however it is worth merging into master so others can begin polishing.

**Solution:**
- Updated theme colours (dark mode only)
- Updated bill list item
- Updated bill page
- Moved navbar to top of view

### CODE REVIEW

**Comment by thatwasmycat** [comment]
Looking great! @oscarmanderj

**Review by thatwasmycat — COMMENTED** [review]
All good :) 👍

**Comment by KipCrossing** [comment]
I'm getting pdf_viewer problems on this one

```red
lib/ui/views/bills/pdf_viewer.dart:104:14: Error: The method 'PdfViewer' isn't defined for the class '_PdfWidgetState'.
 - '_PdfWidgetState' is from 'package:voting_app/ui/views/bills/pdf_viewer.dart' ('lib/ui/views/bills/pdf_viewer.dart').
Try correcting the name to the name of an existing method, or defining a method named 'PdfViewer'.
      return PdfViewer(
             ^^^^^^^^^
```

The new version breaks our app. We aren't going to be using this anyway.

The temp fix that I added in `stable` is:

https://github.com/voteflux/voting_app/blob/de84cae5b2da748fe506827e1a640dd1834e5837/lib/ui/views/bills/bill_view.dart#L127

Using:

```dart
import 'package:url_launcher/url_launcher.dart';
```

**Review by KipCrossing — APPROVED** [review]

**Comment by KipCrossing** [comment]
This PR is good as now we will all be aligned with the theme colors when branching off the master branch.

**Pull request merged**
