### PR TITLE
Design/layout

### PR DESCRIPTION
**Pull request by oscarmanderj**
- Update main.dart to allow stateful transitions between main pages
- Account page rework
- Created dedicated settings page
- General styling updates across whole app

### CODE REVIEW

**Comment by KipCrossing** [comment]
Great work @oscarmanderj! It's looking really good.

I did notice that the web version looks a bit off in the chrome browser. For example, the login fields stretch across the width of the window. See in [bill.dart](https://github.com/voteflux/voting_app/blob/62ceb4e85b99da6590833948c54b3ee209e438d3/lib/bill.dart#L19) how I solved this. Would you like me to fix it or would you like to give ita go?

For web, run:
`flutter run -d chrome`

**Comment by ptboyer** [comment]
Just built this branch on iOS, noticed that the app title "DigiPol" is white on light background, and dark mode doesn't actually change the color of the navigation bar either.

image 
image

- [ ] So we need to toggle the iOS status bar content to "dark-content" on light theme, and "light-content" on dark theme to ensure that the OS time/status/etc is visible on either mode
- [ ] Need the navigation title bar to respect the theme settings also, background/text color.
- [ ] Need the tab bar to also respect the theme also.

Additionally, I think the "current tab" emphasis is not obvious at all:

- [ ] Need to highlight the current tab icon with an accent color for the app, which I would assume is blue, as also denoted by the current button colors in the app on the settings page.

Other than that, the app looks really good, and I appreciate the code restructuring for putting the scenes in a folder etc.

Nice work!

**Comment by ptboyer** [comment]
Between last comment and now new commits have been pushed.

Resolved all the previous notes. Awesome!

**Comment by ptboyer** [comment]
Actually, iOS needs the update the status bar for dark theme with "light-content".

image

**Comment by ptboyer** [comment]
All good, I made the fixes myself.

Actually really liking Flutter/Dart. Nice!

**Pull request merged**
