### PR TITLE
fix #137 - bump flutter_svg to ^0.18.1

### LINKED ISSUE #137: flutter_svg ^0.17.4 is causing ios build to fail
The flutter_svg plugin version ^0.17.4 causes the ios build to fail. Using `flutter build ios --no-codesign`, error below.

It seems this is not an issue when using flutter_svg ^0.18.0 as I found [here](https://github.com/dnfield/flutter_svg/issues/368)

Is there any objection to bumping the version @oscarmanderj ?
*Change log can be found [here](https://pub.dev/packages/flutter_svg/changelog)*

```
Running Xcode build...                                                  
                                                   
Xcode build done.                                           32.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:26: Error: Type
    'DiagnosticableMixin' not found.
    class PictureStream with DiagnosticableMixin {
                             ^^^^^^^^^^^^^^^^^^^
    ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:192:44: Error: Type
    'DiagnosticableMixin' not found.
    abstract class PictureStreamCompleter with DiagnosticableMixin {
                                               ^^^^^^^^^^^^^^^^^^^
    ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:7: Error: The type
    'DiagnosticableMixin' can't be mixed in.
    class PictureStream with DiagnosticableMixin {
          ^
    ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:192:16: Error: The type
    'DiagnosticableMixin' can't be mixed in.
    abstract class PictureStreamCompleter with DiagnosticableMixin {
                   ^
    ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:167:11: Error: Superclass has
    no method named 'debugFillProperties'.
        super.debugFillProperties(properties);
              ^^^^^^^^^^^^^^^^^^^
    ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:171:30: Error: The method
    'toStringShort' isn't defined for the class 'PictureStreamCompleter'.
     - 'PictureStreamCompleter' is from 'package:flutter_svg/src/picture_stream.dart'
     ('../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart').
    Try correcting the name to the name of an existing method, or defining a method named 'toStringShort'.
          ifPresent: _completer?.toStringShort(),
                                 ^^^^^^^^^^^^^
    ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:266:11: Error: Superclass has
    no method named 'debugFillProperties'.
        super.debugFillProperties(description);
              ^^^^^^^^^^^^^^^^^^^

    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Encountered error while building for device.
```

### PR DESCRIPTION
**Pull request by XertroV**
**Problem:**
fix #137 

**Solution:**
bump flutter_svg to ^0.18.1

### CODE REVIEW

**Comment by XertroV** [comment]
Updating the README was done in part to re-trigger goals (which now include `flutter upgrade` so that should fix that stuff)

**Review by connorhsm — DISMISSED** [review]

**Comment by XertroV** [comment]
Note: the test stuff isn't being recorded but it is running, not sure why -- failing on macos last time it ran

**Comment by XertroV** [comment]
hmm not all jobs running still :/

**Review by connorhsm — APPROVED** [review]

**Comment by XertroV** [comment]
note: ios tests still failing - but can't get the status to show up :/ dunno why

**Comment by XertroV** [comment]
So weird, I mean it's running -- this is from just now triggered by the merge to master:

```
s/debug.plist' '-allowProvisioningUpdates'\nSpawned: /var/folders/cf/bthd70hx0px6vgrn8nh4b1bm0000gn/T/atm-93312-93312vkFz6G1Re1Ef ==> cp 'ios/build/Runner.ipa' 'ios/build/fluxApp-debug.ipa' (PID 97315)\nChild process close with code 0 and signal null: /var/folders/cf/bthd70hx0px6vgrn8nh4b1bm0000gn/T/atm-93312-93312vkFz6G1Re1Ef ==> cp 'ios/build/Runner.ipa' 'ios/build/fluxApp-debug.ipa'\nSpawned: /var/folders/cf/bthd70hx0px6vgrn8nh4b1bm0000
gn/T/atm-93312-93312vkFz6G1Re1Ef ==> cp 'ios/build/Runner.ipa' 'ios/build/fluxApp-latest.ipa' (PID 97316)\nChild process close with code 0 and signal null: /var/folders/cf/bthd70hx0px6vgrn8nh4b1bm0000gn/T/atm-93312-93312vkFz6G1Re1Ef ==> cp 'ios/build/Runner.ipa' 'ios/build/fluxApp-latest.ipa'\n"}
Duration: 2m 11s
Finish: 2020-08-30 23:34:35.270
\--
2020-08-30T23:34:44.255Z [m:93312:c6e39a53-745c-4eec-a842-43ca01dd16b1:Flux:FulfillGoalOnRequested:3134] [info ] Starting goal 'Flutter-Ios-Test#goalCreator.ts:85' on 'voteflux/voting_app/master'
2020-08-30T23:35:04.871Z [m:93312:c6e39a53-745c-4eec-a842-43ca01dd16b1:Flux:FulfillGoalOnRequested:23750] [info ] ///--(batch-0: flutter '"upgrade"' )--
2020-08-30T23:35:09.037Z [m:93312:c6e39a53-745c-4eec-a842-43ca01dd16b1:Flux:FulfillGoalOnRequested:27916] [info ] \\\--(batch-0)--
2020-08-30T23:35:09.037Z [m:93312:c6e39a53-745c-4eec-a842-43ca01dd16b1:Flux:FulfillGoalOnRequested:27916] [info ] ///--(batch-1: flutter '"--version
"' )--
2020-08-30T23:35:10.304Z [m:93312:c6e39a53-745c-4eec-a842-43ca01dd16b1:Flux:FulfillGoalOnRequested:29183] [info ] \\\--(batch-1)--
2020-08-30T23:35:10.305Z [m:93312:c6e39a53-745c-4eec-a842-43ca01dd16b1:Flux:FulfillGoalOnRequested:29184] [info ] ///--(batch-2: flutter '"doctor"'
'"-v"' )--
2020-08-30T23:35:15.316Z [m:93312:c6e39a53-745c-4eec-a842-43ca01dd16b1:Flux:FulfillGoalOnRequested:34195] [info ] \\\--(batch-2)--
2020-08-30T23:35:15.316Z [m:93312:c6e39a53-745c-4eec-a842-43ca01dd16b1:Flux:FulfillGoalOnRequested:34195] [info ] ///--(batch-3: flutter '"precache"
' )--
2020-08-30T23:35:17.207Z [m:93312:c6e39a53-745c-4eec-a842-43ca01dd16b1:Flux:FulfillGoalOnRequested:36086] [info ] \\\--(batch-3)--
2020-08-30T23:35:17.207Z [m:93312:c6e39a53-745c-4eec-a842-43ca01dd16b1:Flux:FulfillGoalOnRequested:36086] [info ] ///--(batch-4: flutter '"packages"
' '"get"' )--
```

**Comment by XertroV** [comment]
iOS test output (partial)

```
00:17 +3 -2: /private/var/folders/cf/bthd70hx0px6vgrn8nh4b1bm0000
gn/T/atm-93312-93312mL41wO67kOxB/test/services/wallet_test.dart: Wallet wallet ethereum address should be valid                       \r00:18 +3 -2: /private/var/folders/cf/bthd70hx0px6vgrn8nh4b1bm0000gn/T/atm-93312-93312mL41wO67kOxB/test/services/wallet_test.dart: Wallet wallet ethereum address should be valid                       \r00:19 +3 -2: /private/var/folders/cf/bthd70hx0px6vgrn8nh4b1bm0000gn/T/atm-93312-93312mL41wO67kOxB/test/serv
ices/wallet_test.dart: Wallet wallet ethereum address should be valid                       \r00:20 +3 -2: /private/var/folders/cf/bthd70hx0px6vgrn8nh4b1bm0000gn/T/atm-93312-93312mL41wO67kOxB/test/services/wallet_test.dart: Wallet wallet ethereum address should be valid                       \r00:20 +4 -2: /private/var/folders/cf/bthd70hx0px6vgrn8nh4b1bm0000gn/T/atm-93312-93312mL41wO67kOxB/test/services/wallet_test.dart: Wallet wallet ether
eum address should be valid                       \r00:20 +4 -2: /private/var/folders/cf/bthd70hx0px6vgrn8nh4b1bm0000gn/T/atm-93312-93312mL41wO67kOxB/test/services/wallet_test.dart: Wallet loading empty wallet file should fail                         \r00:20 +5 -2: /private/var/folders/cf/bthd70hx0px6vgrn8nh4b1bm0000gn/T/atm-93312-93312mL41wO67kOxB/test/services/wallet_test.dart: Wallet loading empty wallet file should fail
        \r00:20 +5 -2: /private/var/folders/cf/bthd70hx0px6vgrn8nh4b1bm0000gn/T/atm-93312-93312mL41wO67kOxB/test/services/wallet_test.dart: Wallet make wallet from random mnemomic                              \r00:21 +5 -2: /private/var/folders/cf/bthd70hx0px6vgrn8nh4b1bm0000gn/T/atm-93312-93312mL41wO67kOxB/test/services/wallet_test.dart: Wallet make wallet from random mnemomic                              \r00:22 +5 -2: /private/var/folder
s/cf/bthd70hx0px6vgrn8nh4b1bm0000gn/T/atm-93312-93312mL41wO67kOxB/test/services/wallet_test.dart: Wallet make wallet from random mnemomic                              \r00:23 +5 -2: /private/var/folders/cf/bthd70hx0px6vgrn8nh4b1bm0000gn/T/atm-93312-93312mL41wO67kOxB/test/services/wallet_test.dart: Wallet make wallet from random mnemomic                              \r00:23 +6 -2: /private/var/folders/cf/bthd70hx0px6vgrn8nh4b1bm0000gn/T/atm-
93312-93312mL41wO67kOxB/test/services/wallet_test.dart: Wallet make wallet from random mnemomic                              \r00:23 +6 -2: /private/var/folders/cf/bthd70hx0px6vgrn8nh4b1bm0000gn/T/atm-93312-93312mL41wO67kOxB/test/services/wallet_test.dart: Wallet making wallet with known mnemonic should generate correct key \r00:24 +6 -2: /private/var/folders/cf/bthd70hx0px6vgrn8nh4b1bm0000gn/T/atm-93312-93312mL41wO67kOxB/test/services/wall
et_test.dart: Wallet making wallet with known mnemonic should generate correct key \r00:25 +6 -2: /private/var/folders/cf/bthd70hx0px6vgrn8nh4b1bm0000gn/T/atm-93312-93312mL41wO67kOxB/test/services/wallet_test.dart: Wallet making wallet with known mnemonic should generate correct key \r00:26 +6 -2: /private/var/folders/cf/bthd70hx0px6vgrn8nh4b1bm0000gn/T/atm-93312-93312mL41wO67kOxB/test/services/wallet_test.dart: Wallet making wallet with kn
own mnemonic should generate correct key \r00:26 +7 -2: /private/var/folders/cf/bthd70hx0px6vgrn8nh4b1bm0000gn/T/atm-93312-93312mL41wO67kOxB/test/services/wallet_test.dart: Wallet making wallet with known mnemonic should generate correct key \r00:26 +7 -2: Some tests failed.                                                                                                                                                                        \
nChild process close with code 1 and signal null: /var/folders/cf/bthd70hx0px6vgrn8nh4b1bm0000gn/T/atm-93312-93312mL41wO67kOxB ==> flutter 'test'\n"}}}
Duration: 1m 7s
Finish: 2020-08-30 23:35:50.839
\--
```

**Pull request merged**
