### PR TITLE
[WIP] Start of blockchain sc docs

### PR DESCRIPTION
**Pull request by XertroV**

### CODE REVIEW

**Comment by XertroV** [comment]
Still WIP

**Comment by XertroV** [comment]
@KipCrossing see test blockchain instructions in f2e5cd8

**Comment by KipCrossing** [comment]
It might be nice to include some "pre-reading" links for non-eth people too. @bazmatic @XertroV

**Comment by KipCrossing** [comment]
Whats the status of this one?

**Comment by KipCrossing** [comment]
Reference: https://github.com/voteflux/voting-alpha/issues/9

**Pull request closed without merging**
