### PR TITLE
Fix master 2020 10

### PR DESCRIPTION
**Pull request by XertroV**
fix up master -- doesn't run atm (but I think it does build) and has issues with initializing state and SilverList (or whatever it's called)

### CODE REVIEW

**Comment by KipCrossing** [comment]
I've created a new branch that builds: https://github.com/voteflux/voting_app/tree/stable

**Comment by XertroV** [comment]
> I've created a new branch that builds: https://github.com/voteflux/voting_app/tree/stable

FYI if you work off that branch you will end up with merge conflicts with master.

If we don't get master fixed up it'll be more of a PITA later. From memory it builds. I might have unpushed work (windows got into a boot loop while I was working on things on Wednesday -- that install is in data-recovery land now).

**Comment by KipCrossing** [comment]
I ended up using it to make a tag (v0.1.4). Agreed, we shouldn't build upon the stable branch and fix master instead. But we should have a stable branch in case someone wants to build the app from the source code.

**Comment by XertroV** [comment]
@KipCrossing @oscarmanderj - Just pushed my uncommitted changes from broken windows install to this branch

**Review by oscarmanderj — APPROVED** [review]

**Pull request merged**
