### PR TITLE
Bug/search

### PR DESCRIPTION
**Pull request by oscarmanderj**
- Adds text when no bills are found.
- Searching bills also includes the summary.

Fixes:
#132 
#134

### CODE REVIEW

**Review by KipCrossing — APPROVED** [review]
Fixed the chart problem (new commit in this PR).

All good now

**Comment by KipCrossing** [comment]
Also, all the tests pass on my local.

In *Atomist* I see:

```
HiveError: Box not found. Did you forget to call Hive.openBox()?
```

**Comment by KipCrossing** [comment]
Fails only for iOS. @connorhsm @XertroV can you try build?

Same problem with #139

**Comment by connorhsm** [comment]
I can't get my environment functioning again for reasons unrelated to this change.

From my testing, the error causing the ios test to fail was introduced [by this commit](https://github.com/voteflux/voting_app/commit/8e6d1fa925c3ac9ae27cb1425480fe706f3202a2).

**Review by connorhsm — COMMENTED** [review]
I can't get my environment functioning again for reasons unrelated to this change.

From my testing, the error causing the ios test to fail was introduced [by this commit](https://github.com/voteflux/voting_app/commit/8e6d1fa925c3ac9ae27cb1425480fe706f3202a2).

**Comment by KipCrossing** [comment]
Looks like it's a hive thing, being picked up with `sdm/sdm-flux-ios `

**Comment by XertroV** [comment]
I just merged it b/c if we have a random bug we can't reproduce that shouldn't halt everything.

**Pull request merged**
